name: Criação do pacote .zip para release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Nome da tag do release'
        required: true
        default: 'V1.0.0'
      release_name: 
        description: 'Nome do release'
        required: true
        default: '1.0.0'
      prerelease:
        description: 'Indica se o release é um pre-release'
        required: false
        default: false
        type: boolean

permissions:
  contents: write   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: criar o pacote .zip
        id: create_zip
        run: |
         ZIP_FILE="release-${{ github.event.inputs.tag_name }}.zip"
         git archive -o $ZIP_FILE HEAD
         echo "zip_file=$ZIP_FILE" >> $GITHUB_OUTPUT
      - name: criar release no GitHub
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.release_name }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
          body: "Release ${{ github.event.inputs.release_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fazer upload do pacote .zip para o release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.create_zip.outputs.zip_file }}
          asset_name: ${{ steps.create_zip.outputs.zip_file }}
          asset_content_type: application/zip